In [ ]:
import numpy as np 
import pandas as pd

**Creating a DataFrame**

In [6]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York','Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [7]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
column = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns = column)

#in lists we dont provide a name that's why in the title we see 0,1,...(default)

In [18]:
df2 #hence we can create series with both lists and dic.. but in list we have to name columns manually.

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting and Indexing of Columns**

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
df2['Name'] #Selecting a column

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [26]:
df2[['Name','City']] #selecting multiple column

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating a new column**

In [53]:
df2['Designation'] = ['Doctor', 'Eng.', 'Artist', 'Chef']
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Artist
3  Linda   42    London   85000        Chef

**Removing Columns**

In [54]:
df2.drop('Age', axis = 1) 

# on default its set to 0 so if u dont provide it will give error
# BUT the removed item is not erased from the memory..

    Name      City  Salary Designation
0   John  New York   65000      Doctor
1   Anna     Paris   70000        Eng.
2  Peter    Berlin   62000      Artist
3  Linda    London   85000        Chef

In [55]:
df2.drop('Designation', axis = 1, inplace = True)

In [57]:
df2 #using inplace permanently removes item

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting Rows**

In [58]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [60]:
df2.loc[0] #location is for selecting rows.

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [62]:
df2.loc[[0,1]] #selecting multiple rows

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [63]:
df2.iloc[3] #one more way of selecting row

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

**Selecting Subsets of Row and Columns**

In [66]:
df.loc[[0,1]][['City', 'Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [67]:
df.loc[[2,3]][['Name', 'Age']]

    Name  Age
2  Peter   29
3  Linda   42

**Conditional Selection**

In [68]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# only want to see those people whose age is above 30

In [69]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [73]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000