In [1]:
import numpy as np
import pandas as pd

**Finding Missing Data**

In [3]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
#nan is Not A Number

In [4]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [5]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
df.isna().sum() # sum of number of NA values

A    1
B    1
C    2
D    3
dtype: int64

In [10]:
df.isna().any() # checks if any column has atleast 1 na value

A    True
B    True
C    True
D    True
dtype: bool

**Removing Missing Data**

In [11]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [13]:
df.dropna() # drop na works on rows. drops all the rows having atleat 1 na..if no threshold is provided

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [14]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [17]:
df.dropna(thresh = 3) #keeps rows having atleast 3 NON-NA value

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

**Filling the missing Data**

In [18]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [21]:
df.fillna(0) 
# just an example.. to fix the na value use inplace

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [26]:
values = {
    'A': 100,
    'B': 200,
    'C': 300,
    'D': 400
}
df.fillna(value = values)
# fill hoga COLUMN WISE
# drop and select hoga ROW WISE

       A      B      C      D
0    1.0  200.0    1.0    1.0
1    2.0    2.0    2.0  400.0
2  100.0    3.0    3.0  400.0
3    4.0    4.0  300.0  400.0
4    5.0    5.0  300.0    5.0

In [27]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0